# Generated by Django 3.0.8 on 2020-09-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_update',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
